version: '3.6'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper

  incimanager:
    build:
      context: .
    image: arquisoft/incimanager_e3b
    ports:
      - "8091:8091"
    links:
      - zookeeper
      - kafka

  ### Incidences consumer (InciDashboard mock):
  kafka-consumer:
    image: wurstmeister/kafka
    environment:
      HOST_IP: kafka
      ZK: zookeeper:2181
    command: /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic incidences --from-beginning
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kafka

